---
- include_tasks: "{{ ansible_distribution | lower }}_packages.yml"
  tags:
    - install

- name: Load wireguard module
  modprobe:
    name: wireguard
    state: present

- name: Create /etc/wireguard
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root

- include_tasks: configure_network.yml
  with_items: "{{ wireguard_networks }}"
  tags:
    - configure
