---
- name: Add Ubuntu repositories
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install wireguard
  package:
    name:
      - linux-headers-generic
      - wireguard
    state: present
